/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import ProductBidAdd from './pages/ProductControl/ProductBid/components/FilterTable/components/AddBid';
import ProductBidList from './pages/ProductControl/ProductBid';
import EventActivity from './pages/EventControl/EventActivity';
import AgencyUserAdd from './pages/AgentControl/UserControl/components/AddSysUser';
import AgencyUserList from './pages/AgentControl/UserControl';
import AgencyRoleAdd from './pages/AgentControl/RoleControl/components/AddRole';
import AgencyRoleList from './pages/AgentControl/RoleControl';
import AgencyMenuAdd from './pages/AgentControl/MenuControl/components/AddMenu';
import AgencyMenuList from './pages/AgentControl/MenuControl';
import ShopOrderShow from './pages/ShopControl/ShopOrder/components/FilterTable/ShopOrderShow';
import ShopOrderList from './pages/ShopControl/ShopOrder';
import ShopAddressList from './pages/ShopControl/ShopAddress';
import ShopMenuAdd from './pages/ShopControl/ShopMenu/components/FilterTable/components/AddMenu';
import ShopMenuList from './pages/ShopControl/ShopMenu';
import ShopProductAdd from './pages/ShopControl/ShopList/components/FilterTable/components';
import ShopProductList from './pages/ShopControl/ShopList';
import UserListEdit from './pages/UserControl/Userlist/components/FilterTable/components/EditDialog';
import UserShowCount from './pages/UserControl/Userlist/components/FilterTable/components/ShowCount';
import UserCount from './pages/UserControl/UserCount';
import UserCoupon from './pages/UserControl/UserCoupon';
import ShowUserDetails from './pages/UserControl/Userlist/components/FilterTable/components/ShowUser';
import CapitalChange from './pages/CapitalControl/CapitalChange';
import CapitalOut from './pages/CapitalControl/CapitalOut';
import CapitalIn from './pages/CapitalControl/CapitalIn';
import AddSysRole from './pages/SysPermission/RoleControl/components/AddRole';
import AddSysUser from './pages/SysPermission/SysUserControl/components/AddSysUser';
import AddSysMenu from './pages/SysPermission/MenuControl/components/AddMenu/index';
import RoleControl from './pages/SysPermission/RoleControl';
import SysUserControl from './pages/SysPermission/SysUserControl';
import MenuControl from './pages/SysPermission/MenuControl';
import UserFeedback from './pages/UserControl/UserFeedback';
import Userlist from './pages/UserControl/Userlist';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import Dashboard from './pages/Common/Dashboard';
import BlankLayout from './layouts/BlankLayout';
import Login from './pages/Common/Login';
import NotFound from './pages/Common/NotFound';

const autoGeneratedRoutes = [{
  path: '/product/bid',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: ProductBidAdd
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ProductBidList
  }
},{
  path: '/event/activity',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: EventActivity
  }
},{
  path: '/agency/user',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AgencyUserAdd
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AgencyUserList
  }
},{
  path: '/agency/role',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AgencyRoleAdd
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AgencyRoleList
  }
},{
  path: '/agency/menu',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AgencyMenuAdd
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AgencyMenuList
  }
},{
  path: '/shop/order',
  childRoutes: [{
    path: 'show',
    childRoutes: [],
    indexRoute: {
      component: ShopOrderShow
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ShopOrderList
  }
},{
  path: '/shop/address',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ShopAddressList
  }
},{
  path: '/shop/menu',
  childRoutes: [
    {
      path: 'add',
      childRoutes: [],
      indexRoute: {
        component: ShopMenuAdd
      }
    },{
      path: 'update',
      childRoutes: [],
      indexRoute: {
        component: ShopProductAdd
      }
    }
  ],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ShopMenuList
  }
}, {
  path: '/shop/product',
  childRoutes: [
    {
      path: 'add',
      childRoutes: [],
      indexRoute: {
        component: ShopProductAdd
      }
    }
  ],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ShopProductList
  }
},{
  path: '/user/count',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserCount
  }
},{
  path: '/user/coupon',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserCoupon
  }
},{
  path: '/funds/moneyChange',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CapitalChange
  }
}, {
  path: '/funds/moneyOut',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CapitalOut
  }
}, {
  path: '/funds/moneyIn',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CapitalIn
  }
}, {
  path: '/sysPermission/roleControl',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AddSysRole
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: RoleControl
  }
}, {
  path: '/sysPermission/sysUserControl',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AddSysUser
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: SysUserControl
  }
}, {
  path: '/sysPermission/menu',
  childRoutes: [{
    path: 'add',
    childRoutes: [],
    indexRoute: {
      component: AddSysMenu
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: MenuControl
  }
}, {
  path: '/user/feedback',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserFeedback
  }
}, {
  path: '/user/list',
  childRoutes: [{
    path: 'details',
    childRoutes: [],
    indexRoute: {
      component: ShowUserDetails
    }
  }, {
    path: 'count',
    childRoutes: [],
    indexRoute: {
      component: UserShowCount
    }
  }, {
    path: 'edit',
    childRoutes: [],
    indexRoute: {
      component: UserListEdit
    }
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Userlist
  }
}, {
  path: '/login',
  childRoutes: [],
  component: BlankLayout,
  indexRoute: {
    component: Login
  }
}, {
  path: '/',
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Dashboard
  }
}];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
